include: package:pedantic/analysis_options.yaml
# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    unnecessary_this: false   
    use_function_type_syntax_for_parameters: false
    omit_local_variable_types: false
    prefer_single_quotes: false
    unnecessary_new: false
    
# analyzer:
#   exclude: [build/**]
#   errors:
#     uri_has_not_been_generated: ignore
#   # Angular plugin support is in beta. You're welcome to try it and report
#   # issues: https://github.com/dart-lang/angular_analyzer_plugin/issues
#   plugins:
#     - angular