name: gcx_grand_scss
description: Bootstrap Design Insp Control Panel  scss
version: 1.0.1
author: TLM <source@legionmarket.com>
environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.1.2
  sass_builder: ^2.1.2
  pedantic: ^1.0.3