git clone https://github.com/angular-examples/lottery.git
git clone https://github.com/angular-examples/template-syntax.git
git clone https://github.com/angular-examples/structural-directives.git
git clone https://github.com/angular-examples/user-input.git
git clone https://github.com/angular-examples/toh-6.git
git clone https://github.com/angular-examples/toh-5.git
git clone https://github.com/angular-examples/toh-4.git
git clone https://github.com/angular-examples/toh-3.git
git clone https://github.com/angular-examples/toh-2.git
git clone https://github.com/angular-examples/toh-1.git
git clone https://github.com/angular-examples/toh-0.git
git clone https://github.com/angular-examples/server-communication.git
git clone https://github.com/angular-examples/security.git
git clone https://github.com/angular-examples/router.git
git clone https://github.com/angular-examples/quickstart.git
git clone https://github.com/angular-examples/pipes.git
git clone https://github.com/angular-examples/lifecycle-hooks.git
git clone https://github.com/angular-examples/hierarchical-dependency-injection.git
git clone https://github.com/angular-examples/forms.git
git clone https://github.com/angular-examples/displaying-data.git
git clone https://github.com/angular-examples/dependency-injection.git
git clone https://github.com/angular-examples/component-styles.git
git clone https://github.com/angular-examples/attribute-directives.git
git clone https://github.com/angular-examples/architecture.git