name: app
description: PWA funnel based on Bootstrap
version: 1.0.2
homepage: https://www.trhosting.com
author: TRH Hosting <source@trhhosting.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.11.0
  angular_forms: ^2.1.1
  angular_router: ^2.0.0-alpha+21
  bootstrap_scss:
    git: https://github.com/dart-land/bootstrap_scss
  tlmThemeLogic:
    git: https://gitlab.com/trhhosting/tlmThemeLogic
#  gcx_grand_scss:
#    git: https://gitlab.com/trhhosting/gcx_grand_scss
  gcx_grand_scss:
    path: ../gcx_grand_scss
  http_client: ^1.0.3
  logic:
    # path: /Source/dart/logic
    git: https://gitlab.com/trhhosting/logic.git
  js: ^0.6.2  
  htmlcomp:
    git: https://gitlab.com/trhhosting/htmlcomp.git 
  gcxtrk: 
    git: https://gitlab.com/trhhosting/gcxtrk.git
dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.5.1
  sass_builder: ^2.1.2
